version: "3.8"

services:

  app:
    build: .
    env_file:
       - .env 
    environment:
      MONGO_URL: ${MONGO_URL}
      JWT_SECRET: ${JWT_SECRET}
      API_PORT: ${API_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: bash -c "npm rebuild bcrypt --build-from-source && npx nodemon --legacy-watch api/index.js"

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017 #Usar docker-compose-override para mapear externamente o multistage
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - './volumes/mongo:/data/db'